#!/bin/bash
# Encode a rendered WAV for distribution.
#
# MP3 is encoded at 320 kbps CBR with forced left/right stereo (no joint
# stereo). The entrainment layer depends on each channel keeping its own
# carrier, so mid/side encoding is deliberately disabled.
#
# Usage: scripts/encode.sh renders/<name>.wav
set -euo pipefail

wav="$1"
base="${wav%.wav}"

ffmpeg -hide_banner -loglevel error -y -i "$wav" \
  -c:a libmp3lame -b:a 320k -joint_stereo 0 \
  -metadata title="$(basename "$base")" \
  -metadata artist="Enlightenment (open experiment)" \
  -metadata comment="Reproducible render; parameters in filename. github.com/CitadelAI-Atlas/enlightenment" \
  "$base.mp3"

# Embed movement chapters when a matching ffmetadata file exists
# (generated by scripts/cuesheet.py).
if [ -f "$base.ffmeta" ]; then
  ffmpeg -hide_banner -loglevel error -y -i "$wav" -i "$base.ffmeta" \
    -map_metadata 1 -c:a aac -b:a 256k "$base.m4a"
else
  ffmpeg -hide_banner -loglevel error -y -i "$wav" \
    -c:a aac -b:a 256k "$base.m4a"
fi

ls -lh "$wav" "$base.mp3" "$base.m4a"
